### ISSUE TITLE
Joomla styling clashes with Wordpress base styling.

### ISSUE THREAD

**Issue by vingle** [mattwire/civicrm-haystacktheme#1]
Joomla specific CSS that I add to `haystack-civicrm-joomla-base.css` clashes with Wordpress styling in `haystack-civicrm-shared.css`, increasing the amount of overrides needed to remove conflicts (e.g. below). For now have added the theme https://github.com/vingle/civicrm-shelford instead as a single standalone file that can be referenced in the custom css url box in Civi settings / Resource URLs.

![image](https://user-images.githubusercontent.com/1175967/53931670-16966700-408e-11e9-8938-80318f6c8ce9.png)

![image](https://user-images.githubusercontent.com/1175967/53931637-f797d500-408d-11e9-97c8-f9cfc39db2a6.png)

**Comment by mattwire** [comment]
Closing as we now have separate shelford / haystack themes in the extension. Haystack does not use the base civicrm.css but shelford does.
