### ISSUE TITLE
I can not open the group tree when there are child groups

### ISSUE THREAD

**Issue by ErikHommel** [mattwire/civicrm-haystacktheme#7]
When I have a group tree I can not open the tree. I do get a symbol that I can click for the action links but no symbol to open the group tree.

**Comment by mattwire** [comment]
Hi @ErikHommel Do you have a screenshot or similar so I can see exactly what is happening?

**Comment by ErikHommel** [comment]
I realised last week that it is due to the responsiveness so if I make my screen smaller they appear again. I will make screenshots.
So it begins like so:
![afbeelding](https://user-images.githubusercontent.com/458090/64099793-77b3a480-cd6a-11e9-8ab0-78ec24e44ace.png)

but when I zoom it becomes:
![afbeelding](https://user-images.githubusercontent.com/458090/64099891-a7fb4300-cd6a-11e9-8bd4-e73a868eaa73.png)

and then I can no longer open the group tree.
Makes sense?

**Comment by mattwire** [comment]
This is caused by the `text-indent: -20px` on that datatable.  The "arrow" is there but hidden behind the green +.

**Comment by ErikHommel** [comment]
So what is to be done now? Is this something that Haystack should be able to cope with (and will) or is it something that should not be there on the datatable and should be fixed in core?

**Comment by mattwire** [comment]
@ErikHommel We don't have responsive datatables in core so that's why we don't see the issue there.  Maybe we can take a look in Barcelona

**Comment by mattwire** [comment]
Moved to https://lab.civicrm.org/extensions/haystacktheme/issues/4
